QuizMVC.Web/Controllers/CategoryAndQuestionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuizMVC.Application.CategoryAndQuestionVm;
using QuizMVC.Application.Interfaces;

namespace QuizMVC.Web.Controllers
{
    [Authorize]
    public class CategoryAndQuestionController : Controller
    {
        private readonly ICategoryAndQuestionService _categoryAndQuestionService;
        public CategoryAndQuestionController(ICategoryAndQuestionService categoryAndQuestionService)
        {
            _categoryAndQuestionService = categoryAndQuestionService;
        }
        [HttpGet]
        public IActionResult ShowCategories()
        {
            var model = _categoryAndQuestionService.GetCategories();
            return View(model);
        }
        [HttpGet]
        public IActionResult AddNewCategory()
        {
            return View(new NewCategoryVm());
        }
        [HttpPost]
        public IActionResult AddNewCategory(NewCategoryVm newCategoryModel)
        {
            var id = _categoryAndQuestionService.AddCategory(newCategoryModel);
            return Redirect("/Home/ShowMenuForUser");
        }
        [HttpGet]
        public IActionResult ShowQuestion()
        {
            var user = User.Identity.Name;
            int id = _categoryAndQuestionService.DrawCategory(user);
            var model = _categoryAndQuestionService.ShowRandomlySelectedQuestion(id, user);
            return View(model);
        }
        [HttpGet]
        public IActionResult CheckAnswer(int IdOfSelectedAnswer)
        {
            var user = User.Identity.Name;
            var result = _categoryAndQuestionService.CheckAnswer(IdOfSelectedAnswer, user);
            return RedirectToAction("ManageScores", "UsersRolesAndScores", result);
        }
        [HttpGet]
        public IActionResult AddNewQuestion()
        {
            var model = new NewQuestionVm()
            {
                Categories = _categoryAndQuestionService.GetCategories()
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult AddNewQuestion(NewQuestionVm model)
        {
            var id = _categoryAndQuestionService.AddQuestion(model);
            return new RedirectResult(Url.Action("ShowNewQuestion", new { Id = id }));
        }
        [HttpGet]
        public IActionResult ShowNewQuestion(int id)
        {
            var question = _categoryAndQuestionService.GetQuestionById(id);
            return View(question);
        }
        [HttpGet]
        public IActionResult ChooseGoodAnswer(int id)
        {
            _categoryAndQuestionService.SetGoodAnswer(id);
            return Redirect("/Home/ShowMenuForUser");
        }
    }
}

QuizMVC.Web/Controllers/CategoryAndQuestionForAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuizMVC.Application.CategoryAndQuestionForAdminVm;
using QuizMVC.Application.Interfaces;
using System;

namespace QuizMVC.Web.Controllers
{
    [Authorize]
    [Authorize(Roles = "Admin, SuperAdmin")]
    public class CategoryAndQuestionForAdminController : Controller
    {
        private readonly ICategoryAndQuestionForAdminService _catAndQueService;
        public CategoryAndQuestionForAdminController(ICategoryAndQuestionForAdminService catAndQueService)
        {
            _catAndQueService = catAndQueService;
        }
        [HttpGet]
        public IActionResult ShowCategoriesForAdmin()
        {
            var model = _catAndQueService.GetCategoriesForAdmin();
            return View(model);
        }
        [HttpGet]
        public IActionResult AddCategory()
        {
            return View(new AddAndEditCategoryAdminVm());
        }
        [HttpPost]
        public IActionResult AddCategory(AddAndEditCategoryAdminVm model)
        {
            model.IsAccepted = true;
            int id = _catAndQueService.AddCategory(model);
            return RedirectToAction("ShowCategoriesForAdmin");
        }
        [HttpGet]
        public IActionResult AcceptCategory(int id)
        {
            _catAndQueService.AcceptCategory(id);
            return RedirectToAction("ShowCategoriesForAdmin");
        }
        [HttpGet]
        public IActionResult DeleteCategory(int id)
        {
            _catAndQueService.DeleteCategory(id);
            return RedirectToAction("ShowCategoriesForAdmin");
        }
        [HttpGet]
        public IActionResult EditCategory(int id)
        {
            var category = _catAndQueService.GetCategoryToEdit(id);
            return View(category);
        }
        [HttpPost]
        public IActionResult EditCategory(AddAndEditCategoryAdminVm model)
        {
            _catAndQueService.EditCategory(model);
            return RedirectToAction("ShowCategoriesForAdmin");
        }
        [HttpGet]
        public IActionResult ShowQuestions()
        {
            var questions = _catAndQueService.ShowQuestionsToAdmin(7, 1, "", 0);
            return View(questions);
        }
        [HttpPost]
        public IActionResult ShowQuestions(int pageSize, int? pageNo, string searchString, int? categoryId)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (!categoryId.HasValue)
            {
                categoryId = 0;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var model = _catAndQueService.ShowQuestionsToAdmin(pageSize, pageNo.Value, searchString, categoryId.Value);
            return View(model);
        }
        [HttpGet]
        public IActionResult DetailsOfQuestion(int id)
        {
            var model = _catAndQueService.DetailsOfQuestion(id);
            return View(model);
        }
        [HttpGet]
        public IActionResult AcceptQuestion(int id)
        {
            _catAndQueService.AcceptQuestion(id);
            return new RedirectResult(Url.Action("DetailsOfQuestion", new { Id = id }));
        }
        public IActionResult AcceptAnswer(int id)
        {
            int idQuestion = _catAndQueService.AcceptAnswer(id);
            return new RedirectResult(Url.Action("DetailsOfQuestion", new { Id = idQuestion }));
        }
        [HttpGet]
        public IActionResult DeleteQuestion(int id)
        {
            _catAndQueService.DeleteQuestion(id);
            return RedirectToAction("ShowQuestions");
        }
        [HttpGet]
        public IActionResult DeleteAnswer(int id)
        {
            int idQuestionOfRemovingAnswer = _catAndQueService.DeleteAnswer(id);
            return new RedirectResult(Url.Action("DetailsOfQuestion", new { Id = idQuestionOfRemovingAnswer }));
        }
        [HttpGet]
        public IActionResult AddQuestion()
        {
            var model = new AddAndEditQuestionAndAnswerAdminVm()
            {
                Categories = _catAndQueService.GetCategoriesForAdmin()
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult AddQuestion(AddAndEditQuestionAndAnswerAdminVm model)
        {
            int id = _catAndQueService.AddQuestion(model);
            return new RedirectResult(Url.Action("ShowNewQuestionAdmin", new { Id = id }));
        }
        [HttpGet]
        public IActionResult ShowNewQuestionAdmin(int id)
        {
            var question = _catAndQueService.DetailsOfQuestion(id);
            return View(question);
        }
        [HttpGet]
        public IActionResult ChooseGoodAnswerAndAcceptAnswersAdmin(int id)
        {
            _catAndQueService.ChooseGoodAnswerAndAcceptAnswers(id);
            return RedirectToAction("ShowQuestions");
        }
        [HttpGet]
        public IActionResult EditQuestion(int id)
        {
            var question = _catAndQueService.GetQuestionToEdit(id);
            question.Categories = _catAndQueService.GetCategoriesForAdmin();
            return View(question);
        }
        [HttpPost]
        public IActionResult EditQuestion(AddAndEditQuestionAndAnswerAdminVm model)
        {
            _catAndQueService.EditQuestion(model);
            int iqOfUpdatingQuestion = model.Id;
            return new RedirectResult(Url.Action("DetailsOfQuestion", new { Id = iqOfUpdatingQuestion }));
        }
        [HttpGet]
        public IActionResult AddExtraAnswersToExistingQuestion(int? id, int idQuestion)
        {
            var answerTemplateToExistingQuestion = new AnswerToAdminVm() { QuestionId = idQuestion, IsAccepted = true };
            return View(answerTemplateToExistingQuestion);
        }
        [HttpPost]
        public IActionResult AddExtraAnswersToExistingQuestion(AnswerToAdminVm model)
        {
            _catAndQueService.AddExtraAnswer(model);
            return new RedirectResult(Url.Action("DetailsOfQuestion", new { Id = model.QuestionId }));
        }
    }
}

QuizMVC.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using QuizMVC.Web.Models;
using System.Diagnostics;

namespace QuizMVC.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("User"))
                {
                    return RedirectToAction("ShowMenuForUser");
                }
                else
                {
                    return RedirectToAction("IndexAfterLogin");
                }
            }
            else
            {
                return View();
            }
        }
        [Authorize]
        public IActionResult IndexAfterLogin()
        {
            return View();
        }
        [Authorize]
        [HttpGet]
        public IActionResult ShowMenuForUser()
        {
            return View();
        }
        [Authorize]
        [Authorize(Roles = "Admin, SuperAdmin")]
        [HttpGet]
        public IActionResult ShowMenuForAdmin()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

QuizMVC.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            background-image: url(https://appforskills1.blob.core.windows.net/background/BackgroundMVC.png);
            background-size: cover;
            margin-left: -100px;
            background-repeat: no-repeat;
        }

    </style>
</head>
<body>
    <center><h1 style="color:white; margin-left: -500px">Witaj w aplikacji Quiz</h1></center>
    <center><h1 style="color: white; margin-left: -500px">Aby przejść do menu zaloguj się,<br /> bądź jeżeli nie masz jeszcze konta to zarejestruj się.</h1></center>
</body>

</html>

QuizMVC.Web/Views/Home/IndexAfterLogin.cshtml
@if (!User.IsInRole("User"))
{
    <h3 style="color:firebrick">Wybierz menu, do którego chcesz przejść:</h3>
    <br />
    <br />
    <br />
    <center>
        <div class="btn btn-secondary btn-lg"><h2><a style="color:white" class="text-decoration-none" asp-controller="Home" asp-action="ShowMenuForAdmin">Menu dla administratora</a></h2></div><br /><br />
        <div class="btn btn-info btn-lg"><h2><a style="color:white" class="text-decoration-none" asp-controller="Home" asp-action="ShowMenuForUser">Menu dla użytkownika</a></h2></div>
    </center>
    @if (User.IsInRole("SuperAdmin"))
    {
        <br />
        <center>
            <div class="btn btn-success btn-lg"><h2><a style="color:white" class="text-decoration-none" asp-controller="UsersRolesAndScores" asp-action="ManageUsersRoles">Panel zarządzania użytkownikami</a></h2></div>
        </center>
    }
}

QuizMVC.Web/Views/Home/ShowMenuForAdmin.cshtml
@{
    ViewData["Title"] = "ShowMenuForAdmin";
}

<center><h1>Menu Główne</h1></center>
<br />
<br />
<br />
<br />
<center>
    <div class="btn btn-primary btn-lg">
        <h1><a style="color:white" class="text-decoration-none" asp-controller="CategoryAndQuestionForAdmin" asp-action="ShowCategoriesForAdmin">Pokaż dostępne kategorie</a></h1>
    </div><br /><br />
    <div class="btn btn-danger btn-lg">
        <h1><a style="color:white" class="text-decoration-none" asp-controller="CategoryAndQuestionForAdmin" asp-action="ShowQuestions">Pokaż dostępne pytania</a></h1>
    </div><br /><br /><br /><br />
</center>
<div class="btn btn-warning btn-lg">
    <h3><a style="color:black" class="text-decoration-none" asp-controller="Home" asp-action="Index">Powrót to ekranu głównego</a></h3>
</div>

QuizMVC.Web/Views/Home/ShowMenuForUser.cshtml
@{
    ViewData["Title"] = "ShowMenuForUser";
}
<div>
    <center><h1>Menu Główne</h1></center>
    <br />
    <br /><br />
    <center>
        <div class="btn btn-danger btn-lg">
            <h2><a style="color:white" class="text-decoration-none" asp-controller="CategoryAndQuestion" asp-action="ShowCategories">Zagraj</a></h2>
        </div><br /><br />
        <div class="btn btn-success btn-lg">
            <h2><a style="color:white" class="text-decoration-none" asp-controller="CategoryAndQuestion" asp-action="AddNewCategory">Dodaj nową kategorię</a></h2>
        </div><br /><br />
        <div class="btn btn-primary btn-lg">
            <h2><a style="color:white" class="text-decoration-none" asp-controller="CategoryAndQuestion" asp-action="AddNewQuestion">Dodaj nowe pytanie do istniejącej kategorii</a></h2>
        </div><br /><br />
        <div class="btn btn-info btn-lg">
            <h2><a style="color:white" class="text-decoration-none" asp-controller="UsersRolesAndScores" asp-action="GetAllScores">Pokaż najlepsze wyniki</a></h2>
        </div><br /><br />
    </center>

    @if (!User.IsInRole("User"))
    {
        <div class="btn btn-dark btn-lg">

            <h3><a style="color:white" class="text-decoration-none" asp-controller="Home" asp-action="Index">Powrót to ekranu głównego</a></h3>
        </div>
    }
    </div>